services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://database:27017/hrSystemDB
      - PORT=8000
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  admin:
    depends_on:
      - backend
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    develop:
      watch:
        - path: ./admin/package.json
          action: rebuild
        - path: ./admin
          target: /app
          action: sync
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always  
    volumes:
      - hrSystemVolume:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - database
    ports:
      - "8081:8081"
    restart: always  
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_BASICAUTH_USERNAME: hrSystemDBAdmin
      ME_CONFIG_BASICAUTH_PASSWORD: R*b*400#

volumes:
  hrSystemVolume:
